### ISSUE TITLE
建议付一张gif在README

### ISSUE THREAD

**Issue by elfgzp** [mayneyao/happygif#1]
例如：
![gif](https://ws4.sinaimg.cn/large/006tNbRwgy1fy2nk7qrarg308c04ohdt.gif)

**Comment by mayneyao** [comment]
![3da69b3c-a25f-454c-adae-351761dbd0dd](https://user-images.githubusercontent.com/6588202/49786035-5da9e000-fd5d-11e8-860d-c9789103d46c.gif)
